services:

  postgres:
    image: postgres:16
    container_name: user-crud-postgres
    environment:
      POSTGRES_DB: industry
      POSTGRES_USER: industry
      POSTGRES_PASSWORD: industry
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U industry -d industry"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-crud-api:
    build: .
    container_name: user-crud-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/industry
      SPRING_DATASOURCE_USERNAME: industry
      SPRING_DATASOURCE_PASSWORD: industry
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
