spring.application.name=backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/industry
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/industry}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:industry}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:industry}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true